name: php-cs-fixer

on:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.KOALA_SECRET }}
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --ansi
      
      - name: Run pint
        run: vendor/bin/pint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply pint changes
          commit_user_name: pemudakoding
          commit_user_email: pemudakoding@gmail.com
          commit_author: Author <pemudakoding@gmail.com>
